logging:
  level:
    root: DEBUG
    org:
      springframework:
        security:
        web: debug
        org:hibernate:
    web: debug

server:
  forward-headers-strategy: native

spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 
            client-secret: 
            scope:
              - profile
              - email
  servlet:
    multipart:
      max-request-size: 100MB
      max-file-size: 100MB
